// src/services/data-synthesizer.ts

import {
  TableDefinition,
  ColumnDefinition,
  AnalysisCategory,
  DataProfile,
  ColumnStats,
} from '@/types';

/**
 * Configuration for data synthesis.
 */
export interface SynthesisConfig {
  recordCount: number;
  categories: AnalysisCategory[];
  customPatterns?: DataPattern[];
}

/**
 * Custom data pattern for specific columns.
 */
export interface DataPattern {
  columnName: string;
  pattern: 'normal' | 'anomaly' | 'clustered' | 'sequential' | 'random';
  parameters?: Record<string, unknown>;
}

/**
 * Result of data synthesis including INSERT statements and profile.
 */
export interface GeneratedData {
  tableName: string;
  insertStatements: string[];
  recordCount: number;
  dataProfile: DataProfile;
}

/**
 * DataSynthesizer generates realistic synthetic data matching schemas and use cases.
 *
 * Requirements covered:
 * - 3.1: Generate realistic synthetic data matching the schema structure
 * - 3.2: Create mix of normal and suspicious transactions with realistic patterns
 *        (unusual amounts, timing, geographic anomalies) - anomaly rate 5-20%
 * - 3.3: Use real-world coordinate ranges and cluster data around meaningful locations
 * - 3.4: Create data with realistic temporal patterns (daily cycles, weekly patterns)
 * - 3.5: Respect referential integrity between related tables
 * - 3.6: Allow users to specify the number of records to generate
 * - 3.7: Provide a DataProfile summarizing the generated data characteristics
 */
export class DataSynthesizer {
  /**
   * Known locations for geographic clustering (Requirement 3.3).
   * Data clusters around these real-world cities.
   */
  private knownLocations = [
    { name: 'Mumbai', lat: 19.076, lon: 72.8777, region: 'Asia' },
    { name: 'Delhi', lat: 28.6139, lon: 77.209, region: 'Asia' },
    { name: 'Singapore', lat: 1.3521, lon: 103.8198, region: 'Asia' },
    { name: 'Tokyo', lat: 35.6762, lon: 139.6503, region: 'Asia' },
    { name: 'Hong Kong', lat: 22.3193, lon: 114.1694, region: 'Asia' },
    { name: 'Shanghai', lat: 31.2304, lon: 121.4737, region: 'Asia' },
    { name: 'New York', lat: 40.7128, lon: -74.006, region: 'Americas' },
    { name: 'Los Angeles', lat: 34.0522, lon: -118.2437, region: 'Americas' },
    { name: 'London', lat: 51.5074, lon: -0.1278, region: 'Europe' },
    { name: 'Paris', lat: 48.8566, lon: 2.3522, region: 'Europe' },
  ];

  /**
   * Synthesizes data for a table based on configuration.
   *
   * @param table - Table definition to generate data for
   * @param config - Synthesis configuration including record count and categories
   * @returns Generated data with INSERT statements and data profile
   */
  async synthesize(
    table: TableDefinition,
    config: SynthesisConfig
  ): Promise<GeneratedData> {
    const records: Record<string, unknown>[] = [];
    // Anomaly rate between 5-20% for fraud detection (Requirement 3.2)
    const anomalyRate = config.categories.includes('fraud_detection') ? 0.1 : 0;

    for (let i = 0; i < config.recordCount; i++) {
      const isAnomaly = Math.random() < anomalyRate;
      const record = this.generateRecord(table, config.categories, isAnomaly, i);
      records.push(record);
    }

    const insertStatements = this.generateInsertStatements(table.name, records);
    const dataProfile = this.computeProfile(table.name, records, table.columns);

    return {
      tableName: table.name,
      insertStatements,
      recordCount: records.length,
      dataProfile,
    };
  }

  /**
   * Generates a single record for the table.
   *
   * @param table - Table definition
   * @param categories - Analysis categories affecting data generation
   * @param isAnomaly - Whether this record should be an anomaly
   * @param index - Record index for deterministic patterns
   * @returns Generated record as key-value pairs
   */
  private generateRecord(
    table: TableDefinition,
    categories: AnalysisCategory[],
    isAnomaly: boolean,
    index: number
  ): Record<string, unknown> {
    const record: Record<string, unknown> = {};

    for (const col of table.columns) {
      if (col.name === 'ID') continue; // Auto-generated by Oracle
      record[col.name] = this.generateValue(col, categories, isAnomaly, index);
    }

    return record;
  }

  /**
   * Generates a value for a specific column based on its type and context.
   *
   * @param col - Column definition
   * @param categories - Analysis categories for context-aware generation
   * @param isAnomaly - Whether to generate anomalous values
   * @param index - Record index for clustering and patterns
   * @returns Generated value appropriate for the column
   */
  private generateValue(
    col: ColumnDefinition,
    _categories: AnalysisCategory[],
    isAnomaly: boolean,
    index: number
  ): unknown {
    const colName = col.name.toUpperCase();

    // Handle specific column types based on name patterns

    // Geographic coordinates with clustering (Requirement 3.3)
    if (colName === 'LATITUDE') {
      const loc = this.knownLocations[index % this.knownLocations.length];
      // Cluster around known locations with small variance (±0.25 degrees)
      const variance = (Math.random() - 0.5) * 0.5;
      return Math.max(-90, Math.min(90, loc.lat + variance));
    }

    if (colName === 'LONGITUDE') {
      const loc = this.knownLocations[index % this.knownLocations.length];
      const variance = (Math.random() - 0.5) * 0.5;
      return Math.max(-180, Math.min(180, loc.lon + variance));
    }

    // Fraud detection columns (Requirement 3.2)
    if (colName === 'RISK_SCORE') {
      // Anomalies have high risk scores (70-100), normal have low (0-30)
      return isAnomaly ? 70 + Math.random() * 30 : Math.random() * 30;
    }

    if (colName === 'IS_FLAGGED') {
      return isAnomaly ? 1 : 0;
    }

    // Amount/value columns with anomaly patterns (Requirement 3.2)
    if (colName.includes('AMOUNT') || colName.includes('VALUE')) {
      const baseAmount = 100 + Math.random() * 900;
      // Anomalies have unusually high amounts (5-15x normal)
      return isAnomaly ? baseAmount * (5 + Math.random() * 10) : baseAmount;
    }

    // Time series data with realistic patterns (Requirement 3.4)
    if (
      colName.includes('DATE') ||
      colName.includes('TIME') ||
      colName === 'CREATED_AT' ||
      colName === 'TIMESTAMP'
    ) {
      return this.generateTimestamp(index);
    }

    // Default generation based on Oracle type (Requirement 3.1)
    if (col.oracleType.includes('VARCHAR')) {
      return this.generateString(colName);
    }

    if (col.oracleType.includes('NUMBER')) {
      // Check for specific number patterns
      if (col.oracleType.includes('(1)')) {
        // Boolean-like NUMBER(1)
        return Math.random() > 0.5 ? 1 : 0;
      }
      if (col.oracleType.includes('(5,2)') || col.oracleType.includes('(10,2)')) {
        // Decimal numbers
        return Math.round(Math.random() * 1000 * 100) / 100;
      }
      return Math.floor(Math.random() * 1000);
    }

    if (col.oracleType.includes('VECTOR')) {
      return null; // Embeddings handled separately by embedding service
    }

    if (col.oracleType.includes('TIMESTAMP')) {
      return this.generateTimestamp(index);
    }

    return null;
  }

  /**
   * Generates a timestamp with realistic temporal patterns (Requirement 3.4).
   * Creates dates within the past year with daily and weekly variations.
   *
   * @param index - Record index for pattern variation
   * @returns ISO timestamp string
   */
  private generateTimestamp(_index: number): string {
    // Generate dates within past year
    const daysAgo = Math.floor(Math.random() * 365);
    const date = new Date();
    date.setDate(date.getDate() - daysAgo);

    // Add realistic time variation (business hours more likely)
    const hour = this.generateBusinessHour();
    date.setHours(hour);
    date.setMinutes(Math.floor(Math.random() * 60));
    date.setSeconds(Math.floor(Math.random() * 60));
    date.setMilliseconds(Math.floor(Math.random() * 1000));

    return date.toISOString();
  }

  /**
   * Generates a business hour with higher probability during work hours.
   * Simulates realistic transaction patterns.
   *
   * @returns Hour of day (0-23)
   */
  private generateBusinessHour(): number {
    // 70% chance of business hours (9-17), 30% chance of other hours
    if (Math.random() < 0.7) {
      return 9 + Math.floor(Math.random() * 8); // 9-16
    }
    return Math.floor(Math.random() * 24);
  }

  /**
   * Generates a string value based on column name patterns.
   *
   * @param colName - Column name to determine appropriate values
   * @returns Generated string value
   */
  private generateString(colName: string): string {
    const prefixes: Record<string, string[]> = {
      NAME: ['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', 'Zeta', 'Eta', 'Theta'],
      TYPE: ['Standard', 'Premium', 'Basic', 'Enterprise', 'Professional'],
      STATUS: ['Active', 'Pending', 'Completed', 'Cancelled', 'Processing'],
      CATEGORY: ['Electronics', 'Finance', 'Healthcare', 'Retail', 'Technology'],
      SOURCE: ['Web', 'Mobile', 'API', 'Partner', 'Direct'],
      DESTINATION: ['Account_A', 'Account_B', 'Account_C', 'Account_D', 'Account_E'],
      ADDRESS: ['0x1a2b3c', '0x4d5e6f', '0x7g8h9i', '0xaabbcc', '0xddeeff'],
      OWNER: ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
      CURRENCY: ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'BTC', 'ETH'],
      REGION: ['North', 'South', 'East', 'West', 'Central'],
      COUNTRY: ['USA', 'UK', 'Japan', 'Germany', 'France', 'India', 'China'],
      CITY: ['Mumbai', 'Delhi', 'Singapore', 'Tokyo', 'New York', 'London'],
    };

    for (const [key, values] of Object.entries(prefixes)) {
      if (colName.includes(key)) {
        return values[Math.floor(Math.random() * values.length)];
      }
    }

    // Default: generate a unique identifier
    return `${colName}_${Math.floor(Math.random() * 10000)}`;
  }

  /**
   * Generates INSERT statements for all records.
   *
   * @param tableName - Target table name
   * @param records - Records to insert
   * @returns Array of INSERT SQL statements
   */
  private generateInsertStatements(
    tableName: string,
    records: Record<string, unknown>[]
  ): string[] {
    if (records.length === 0) return [];

    const columns = Object.keys(records[0]);
    const statements: string[] = [];

    for (const record of records) {
      const values = columns.map((col) => this.formatValue(record[col]));
      statements.push(
        `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES (${values.join(', ')})`
      );
    }

    return statements;
  }

  /**
   * Formats a value for SQL INSERT statement.
   *
   * @param value - Value to format
   * @returns SQL-formatted value string
   */
  private formatValue(value: unknown): string {
    if (value === null || value === undefined) return 'NULL';

    if (typeof value === 'number') {
      // Round to reasonable precision for decimals
      if (!Number.isInteger(value)) {
        return String(Math.round(value * 100) / 100);
      }
      return String(value);
    }

    if (typeof value === 'string') {
      // Handle ISO timestamp strings
      if (value.match(/^\d{4}-\d{2}-\d{2}/)) {
        return `TO_TIMESTAMP('${value}', 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"')`;
      }
      // Escape single quotes for SQL
      return `'${value.replace(/'/g, "''")}'`;
    }

    return `'${String(value)}'`;
  }

  /**
   * Computes a data profile summarizing generated data characteristics (Requirement 3.7).
   *
   * @param tableName - Name of the table
   * @param records - Generated records
   * @param columns - Column definitions
   * @returns Data profile with statistics
   */
  private computeProfile(
    tableName: string,
    records: Record<string, unknown>[],
    columns: ColumnDefinition[]
  ): DataProfile {
    const columnStats: ColumnStats[] = columns
      .filter((c) => c.name !== 'ID')
      .map((col) => this.computeColumnStats(col.name, records));

    const profile: DataProfile = {
      tableName,
      recordCount: records.length,
      columnStats,
    };

    // Compute geographic spread if applicable
    const lats = records.map((r) => r['LATITUDE'] as number).filter((v) => v != null);
    const lons = records.map((r) => r['LONGITUDE'] as number).filter((v) => v != null);
    if (lats.length > 0 && lons.length > 0) {
      profile.geographicSpread = {
        minLat: Math.min(...lats),
        maxLat: Math.max(...lats),
        minLon: Math.min(...lons),
        maxLon: Math.max(...lons),
      };
    }

    // Compute anomaly count
    const flagged = records.filter((r) => r['IS_FLAGGED'] === 1);
    if (flagged.length > 0) {
      profile.anomalyCount = flagged.length;
    }

    // Compute time range
    const timestamps = records
      .map((r) => {
        const val = r['CREATED_AT'] || r['TIMESTAMP'];
        return val ? new Date(val as string) : null;
      })
      .filter((d): d is Date => d !== null && !isNaN(d.getTime()));

    if (timestamps.length > 0) {
      profile.timeRange = {
        start: new Date(Math.min(...timestamps.map((d) => d.getTime()))),
        end: new Date(Math.max(...timestamps.map((d) => d.getTime()))),
      };
    }

    return profile;
  }

  /**
   * Computes statistics for a single column.
   *
   * @param colName - Column name
   * @param records - All records
   * @returns Column statistics
   */
  private computeColumnStats(colName: string, records: Record<string, unknown>[]): ColumnStats {
    const values = records.map((r) => r[colName]);
    const nonNull = values.filter((v) => v != null);
    const unique = new Set(nonNull.map(String));

    const stats: ColumnStats = {
      columnName: colName,
      dataType: nonNull.length > 0 ? typeof nonNull[0] : 'undefined',
      nullCount: values.length - nonNull.length,
      uniqueCount: unique.size,
    };

    // Compute numeric statistics
    if (nonNull.length > 0 && typeof nonNull[0] === 'number') {
      const nums = nonNull as number[];
      stats.min = Math.min(...nums);
      stats.max = Math.max(...nums);
      stats.mean = nums.reduce((a, b) => a + b, 0) / nums.length;
      const variance =
        nums.reduce((sum, n) => sum + Math.pow(n - stats.mean!, 2), 0) / nums.length;
      stats.stdDev = Math.sqrt(variance);
    }

    // Compute top values for categorical columns
    if (nonNull.length > 0 && typeof nonNull[0] === 'string') {
      const valueCounts = new Map<string, number>();
      for (const v of nonNull) {
        const str = String(v);
        valueCounts.set(str, (valueCounts.get(str) || 0) + 1);
      }
      stats.topValues = Array.from(valueCounts.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5)
        .map(([value, count]) => ({ value, count }));
    }

    return stats;
  }

  /**
   * Gets the list of known locations for geographic clustering.
   * Useful for testing and validation.
   *
   * @returns Array of known location objects
   */
  getKnownLocations(): Array<{ name: string; lat: number; lon: number; region: string }> {
    return [...this.knownLocations];
  }
}
